### PR TITLE
Upgrade node-redis to 4.6.1

### PR DESCRIPTION
**Pull request by eatyourgreens**
Follows on from #129, which crashed when it deployed to staging. This should be the same changes in a new PR.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Keeping this as draft until we know why it crashed when it was deployed to staging.

**Comment by eatyourgreens** [comment]
Oh, I'm an idiot. Should have read the documentation more closely. The [new client config option](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md) is `socket.tls`. I'll push a change up.

**Comment by eatyourgreens** [comment]
Seems to be running on staging without problems.👍🏻

**Comment by camallen** [comment]
The explicit client connections are much better - nice work diagnosing the lib bug / upgrade path.

**Comment by eatyourgreens** [comment]
Thanks!

**Pull request merged**
